spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/products/**
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billings/**    
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
